services:
    sessql:
        image: postgres:18.1
        container_name: spoof-entrance-service-db
        environment:
            POSTGRES_DB: SpoofEntranceService
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres123
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - postgres_ses_data:/var/lib/postgresql/data
            - ./SpoofEntranceService/SpoofEntranceService.sql:/docker-entrypoint-initdb.d/init.sql
        restart: unless-stopped
        networks:
            - spoof-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    ssssql:
        image: postgres:18.1
        container_name: spoof-settings-service-db
        environment:
            POSTGRES_DB: SpoofSettingsService
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres123
            PGDATA: /var/lib/postgresql/data/pgdata
        command: ["postgres", "-c", "port=5433"]
        ports:
            - "5433:5433"
        volumes:
            - postgres_sss_data:/var/lib/postgresql/data
            - ./SpoofSettingsService/SpoofSettingsService.sql:/docker-entrypoint-initdb.d/init.sql
        restart: unless-stopped
        networks:
            - spoof-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -p 5433"]
            interval: 10s
            timeout: 5s
            retries: 5

    smssql:
        image: postgres:18.1
        container_name: spoof-message-service-db
        environment:
            POSTGRES_DB: SpoofMessageService
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres123
            PGDATA: /var/lib/postgresql/data/pgdata
        command: ["postgres", "-c", "port=5434"]
        ports:
            - "5434:5434"
        volumes:
            - postgres_sms_data:/var/lib/postgresql/data
            - ./SpoofMessageService/SpoofMessageService.sql:/docker-entrypoint-initdb.d/init.sql
        restart: unless-stopped
        networks:
            - spoof-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -p 5434"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:8.4.0
        container_name: redis-test
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        command: redis-server --appendonly yes --requirepass redis123
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - spoof-network
    spoofentranceservice:
        build:
            context: .
            dockerfile: SpoofEntranceService/Dockerfile
        container_name: spoof-entrance-service
        depends_on:
            - redis
            - sessql
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__Redis=redis:6379,password=redis123,abortConnect=false,connectTimeout=10000
            - Redis__Password=redis123
            - ConnectionStrings__DefaultConnection=Host=sessql;Port=5432;Database=SpoofEntranceService;Username=postgres;Password=postgres123;Pooling=true;Timeout=30;CommandTimeout=30;
        ports:
            - "5000:8080"
        volumes:
            - ./src:/app/src
        networks:
            - spoof-network
    spoofsettingsservice:
        build:
            context: .
            dockerfile: SpoofSettingsService/Dockerfile
        container_name: spoof-settings-service
        depends_on:
            - redis
            - sessql
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__Redis=redis:6379,password=redis123,abortConnect=false,connectTimeout=10000
            - Redis__Password=redis123
            - ConnectionStrings__DefaultConnection=Host=ssssql;Port=5434;Database=SpoofSettingsService;Username=postgres;Password=postgres123;Pooling=true;Timeout=30;CommandTimeout=30;
        ports:
            - "5001:8081"
        volumes:
            - ./src:/app/src
        networks:
            - spoof-network
    spoofmessageservice:
        build:
            context: .
            dockerfile: SpoofMessageSpoofMessageServiceService/Dockerfile
        container_name: spoof-message-service
        depends_on:
            - redis
            - sessql
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__Redis=redis:6379,password=redis123,abortConnect=false,connectTimeout=10000
            - Redis__Password=redis123
            - ConnectionStrings__DefaultConnection=Host=smssql;Port=5433;Database=SpoofMessageService;Username=postgres;Password=postgres123;Pooling=true;Timeout=30;CommandTimeout=30;
        ports:
            - "5002:8082"
        volumes:
            - ./src:/app/src
        networks:
            - spoof-network

volumes:
    redis_data:
        driver: local
    postgres_ses_data:
        driver: local
    postgres_sss_data:
        driver: local
    postgres_sms_data:
        driver: local

networks:
    spoof-network:
        driver: bridge